language: cpp

os: osx
# macOS 10.10
osx_image: xcode8

script: ./build-leptonica-macosx && ./build-tesseract-macosx

deploy:
  provider: releases
  api_key: $GH_OAUTH_TOKEN
  file: tesseract.macos
  skip_cleanup: true
