#! /bin/bash -x

set -e

while [ "$1" ]; do
        case $1 in
                -keep)  
                        KEEP=1
                        shift
                        ;;
                *)
                        echo "Unknown parameter: $1"
                        exit 1
                        ;;
        esac
done

source ./versions.conf

PRISTINE=tesseract-$TESSERACT_VERSION-pristine
BUILD=tesseract-BUILD
TESSERACT_INSTALL=$PWD/tesseract-$TESSERACT_VERSION-install
LEPTONICA=$PWD/leptonica-$LEPTONICA_VERSION-install

if [ ! -d $PRISTINE ]; then
		git clone --branch $TESSERACT_VERSION --depth 1 https://github.com/tesseract-ocr/tesseract.git $PRISTINE
fi

if [ ! "$KEEP" ]; then
        rm -rf $BUILD $TESSERACT_INSTALL
        cp -a $PRISTINE $BUILD
fi

cd $BUILD

./autogen.sh

CFLAGS="-mmacosx-version-min=10.6"
export CFLAGS
./configure --prefix=$TESSERACT_INSTALL --enable-static --disable-shared LEPTONICA_CFLAGS="-I$LEPTONICA/include" LEPTONICA_LIBS="-L$LEPTONICA/lib" LIBS="-lpng -lz"

make

# The binary is not static, do that
cd api
g++ $CFLAGS -g -O2 -o tesseract tesseractmain.o -Wl,-bind_at_load  -L/Users/dbonniot/tesseract/leptonica-1.69-install/lib -L/opt/local/lib ./.libs/libtesseract.a -L./ -L../ -L../api -L../ccutil -L../viewer -L../cutil -L../image -L../ccstruct -L../dict -L../classify -L../wordrec -L../neural_networks/runtime -L../textord -L../cube -L../ccmain /Users/dbonniot/tesseract/leptonica-1.69-install/lib/liblept.a -lpthread /opt/local/lib/libpng15.a /opt/local/lib/libz.a
cd ..

make install-strip
