#! /bin/bash -x

set -e

while [ "$1" ]; do
        case $1 in
                -keep)  
                        KEEP=1
                        shift
                        ;;
                *)
                        echo "Unknown parameter: $1"
                        exit 1
                        ;;
        esac
done

source ./versions.conf

PRISTINE=tesseract-$TESSERACT_VERSION-pristine
BUILD=tesseract-BUILD
TESSERACT_INSTALL=$PWD/tesseract-$TESSERACT_VERSION-install
LEPTONICA=$PWD/leptonica-$LEPTONICA_VERSION-install

if [ ! -d $PRISTINE ]; then
		git clone --branch $TESSERACT_VERSION --depth 1 https://github.com/tesseract-ocr/tesseract.git $PRISTINE
fi

if [ ! "$KEEP" ]; then
        rm -rf $BUILD $TESSERACT_INSTALL
        cp -a $PRISTINE $BUILD
fi

cd $BUILD

./autogen.sh

CFLAGS="-mmacosx-version-min=10.11"
export CFLAGS
./configure --prefix=$TESSERACT_INSTALL --enable-static --disable-shared LEPTONICA_CFLAGS="-I$LEPTONICA/include -iquote $LEPTONICA/include/leptonica" LEPTONICA_LIBS="$LEPTONICA/lib/liblept.la" LIBS="-lpng -lz"

make

# The binary is not static, do that
pushd src/api
g++ $CFLAGS -g -O2 -o tesseract tesseract-tesseractmain.o -Wl,-bind_at_load  -L$LEPTONICA/lib -L/opt/local/lib ./.libs/libtesseract.a -L./ -L../ -L../api -L../ccutil -L../viewer -L../cutil -L../image -L../ccstruct -L../dict -L../classify -L../wordrec -L../neural_networks/runtime -L../textord -L../cube -L../ccmain $LEPTONICA/lib/liblept.a -lpthread /usr/local/lib/libpng16.a -lz
popd

make install-strip

otool -L $TESSERACT_INSTALL/bin/tesseract
wget 'https://github.com/tesseract-ocr/tessdata_fast/raw/master/eng.traineddata' -O $TESSERACT_INSTALL/share/tessdata/eng.traineddata
$TESSERACT_INSTALL/bin/tesseract ../tokkyo_P156.png stdout
